export function has(array: any[], value: any): boolean;
export function isEmpty(value: any): boolean;
export function last(array: any[]): any;
export function next(index: number, array: any[], loop?: boolean): any;
export function prev(index: number, array: any[], loop?: boolean): any;
export function print(value: any, separator?: any): any;
export function push(array: any[], value: any, unique?: boolean): any;
export function random(array: any[]): any;
export function shuffle(array: any[]): any;
export function toArray(...args: any): any;
